export const projects = [
  {
    title: 'Worldwide Covid-19 Tracker',
    description: "Used React-JS in the frontEnd and to fetched data using an free external API, not only this but I used DB.js to give the graphcal visualization of the data, also used npm packages to import the world map visuals.",
      image: '/images/1.png',
      tags: ['React', 'Node','Rest API'],
    visit: 'https://github.com/Preetam078/covid-reaactjs-',
    source: 'https://online-covid19-tracker.web.app/',
    id: 0,
  },
  {
    title: "Decentralised Chat Application",
    description:"This one is the decentralised Chat Application where for the user Interaction I have used NextJS as the frontend Library and for the backend the used a decentralised service called moralis.io",
    image: '/images/2.png',
    tags: ['NextJs', 'JavaScript', 'Moralis', 'ethereum'],
    visit: 'https://github.com/Preetam078/metaverse-challenge',
    source: 'https://metaverse-challenge-theta.vercel.app/',
    id: 1,
  },
  {
    title: 'Google Search Engine Clone',
    description: "This is the Exact replica of the google search engine i tried to make, during the process of development I used NextJS as the frontend Library for the best user Interface as possible for and used Google's Developer API so to the function  data for the project's Dynamics",
      image: '/images/3.png',
      tags: ['NextJS', 'API'],
    visit: 'https://github.com/Preetam078/Googleclone',
    source: 'https://googleclone-six.vercel.app/',
    id: 2,
  },
  {
    title: 'Decentralised Cryptocurries Tranfer App',
    description: "This is the Blockchain project, where the backend is designed in solidity language and deployed in the ethereum test network, and the frontend is Designed using reactJS.",
    image: '/images/4.png',
    tags: ['React', 'NodeJS', 'Solidiy', 'Ethereum', 'Metamask'],
    visit: 'https://github.com/Preetam078/Krypto',
    source: 'https://krypto-beryl.vercel.app/',
    id: 3,
  },
  {
    title: 'Lottery Smart Contract',
    description: "This is the smart contract I made using Solidity in the Ethereum Blockchain Test Network in the famous Remix IDE. here after the participating some numbers of participants the random one who wins get the money automatically",
    image: '/images/5.jpeg',
    tags: ['Solidiy', 'Ethereum', 'Metamask'],
    visit: 'https://github.com/Preetam078/Lottery-Smart-Contract',
    source: 'https://github.com/Preetam078/Lottery-Smart-Contract',
    id: 3,
  },
  {
    title: 'Short Video App Backend',
    description: "This one is the backend Project mainly done using NodeJS, ExpressJS, and used MongoDB Non relational Database to store the data",
    image: '/images/5.jpeg',
    tags: ['NodeJS', 'ExpressJS', 'MongoDB'],
    visit: 'https://github.com/Preetam078/TikTok_Backend',
    source: 'https://github.com/Preetam078/TikTok_Backend',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];